### ISSUE TITLE
Indicator Session Applet: Logout fail

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [mate-desktop-legacy-archive/Mate-Extra#15]
I setup Ubuntu 12.04 daily (2011-4-11) in a virtualbox on ubuntu 10.04
installed mate and the extra applets i tried to logout a few time using the applet but nothing happened
the logout works from the system menu

other stuff i noticed/question i have:
how do you change the date format in the indicator applet complete?
also tried changing my mouse them to DMZ-Black is mate affected by the same bug 10.04 is with that?
in 10.04 i have to manually change the cursor in a .theme file
some themes are missing a engine how do i get those

**Comment by szesch** [comment]
Confirmed on 12.04 beta 2.

**Comment by GM-Script-Writer-62850** [comment]
same issue on linux mint debian 
also this applet has unlisted dependencies like indicator-applet-complete

**Comment by szesch** [comment]
What does your indicator-applet-session.log file look like?

**Comment by GM-Script-Writer-62850** [comment]
Looking at Module: libsession.so
mint USER HAS ACTIVE SESSIONS

**Comment by GM-Script-Writer-62850** [comment]
got that on mint debian live cd which i can reproduce it on and since it have mate installed out of the it was the quickest iso i had to get the results
and indicator-session-gtk2 need to be marked as a dependency of this applet at least on mint debian without that packages the applet just says no indicators

**Comment by szesch** [comment]
The problem is gtk-logout-helper which is part of the indicator-session package. 

*\* (gtk-logout-helper:12926): WARNING **: Unable to get DBus proxy to SessionManager interface: Could not get owner of name 'org.gnome.SessionManager': no such

We have two options: drop support for the indicator applet session, or we can attempt to submit a patch upstream to the devs of indicator-session to get gtk-logout-helper to try org.mate.SessionManager if org.gnome.SessionManager fails.

**Comment by GM-Script-Writer-62850** [comment]
if you drop support will it be replaced, forked, unsupported, or removed?

**Comment by szesch** [comment]
Indicator applet session and indicator applet complete will be removed. Unfortunately, both of those applets depend on indicator-session which in turn depends on gnome-settings-daemon and the existence org.gnome.SessionManager. The standard indicator-applet will still be available.

**Comment by GM-Script-Writer-62850** [comment]
will there be a power button menu applet with the option to shutdown, logoff, suspend, hibernate, lock screen and launch the guest account
option so suppress confirm prompt would be nice

will this affect the indicator icons (like the network manager)

**Comment by szesch** [comment]
The indicator-applet should never have been forked in the first place. It was never a gnome package, but an Ubuntu applet. Because of this, most distros do not have the necessary libraries required to support full functionality of the various indicators. For example, indicator-applet-complete doesn't work on Debain because libappindicator isn't in their repos. 

I have removed the session applet and it will not exist in our 1.4 release. We are tentatively planning on creating our own session applet, but this won't be available until 1.6 at the earliest.  For the time being, we will leave indicator-applet-complete, but this will only work on distros with the necessary libraries. For those that lack the needed libraries, the applet will simply not work to it's fullest potential.
